#Completely remove the following

2048-qt
fonts-beng-extra
fonts-deva-extra
fonts-gubbi
fonts-gujr-extra
fonts-guru-extra
fonts-khmeros-core
fonts-lohit-beng-assamese
fonts-lohit-beng-bengali
fonts-lohit-deva
fonts-lohit-gujr
fonts-lohit-guru
fonts-lohit-knda
fonts-lohit-mlym
fonts-lohit-orya
fonts-lohit-taml
fonts-lohit-taml-classical
fonts-lohit-telu
fonts-noto-cjk
fonts-orya-extra
fonts-pagul
fonts-smc-anjalioldlipi
fonts-smc-chilanka
fonts-smc-dyuthi
fonts-smc-karumbi
fonts-smc-keraleeyam
fonts-smc-manjari
fonts-smc-meera
fonts-smc-rachana
fonts-smc-raghumalayalamsans
fonts-smc-suruma
fonts-smc-uroob
fonts-telu-extra
fonts-tlwg-garuda
fonts-tlwg-kinnari
fonts-tlwg-laksaman
fonts-tlwg-loma
fonts-tlwg-mono
fonts-tlwg-norasi
fonts-tlwg-typist
fonts-tlwg-typo
fonts-tlwg-umpush
fonts-tlwg-waree
k3b-data
libreoffice-base-core
libreoffice-calc
libreoffice-common
libreoffice-core
libreoffice-draw
libreoffice-gtk3
libreoffice-impress
libreoffice-math
libreoffice-qt5
libreoffice-style-breeze
libreoffice-style-colibre
libreoffice-style-tango
libreoffice-writer

compton
compton-conf


lubuntu-default-settings
lximage-qt
lxqt-about
lxqt-admin
lxqt-config
lxqt-notificationd
lxqt-openssh-askpass
lxqt-panel
lxqt-policykit
lxqt-qtplugin
lxqt-runner
lxqt-session
lxqt-sudo
lxqt-system-theme
lxqt-themes
pcmanfm-qt


gxkb
gxneur
libxneur
lightdm-gtk-greeter-settings
texlive-base
texlive-extra-utils
texlive-fonts-recommended
texlive-latex-base
texlive-plain-generic
tipa
xdot
xneur

guile-2.2-libs
keymapper
qlipper
texlive-latex-extra
texlive-latex-recommended
texlive-pictures
xbindkeys


fcitx
fcitx-bin
fcitx-data
fcitx-frontend-gtk2
fcitx-module-dbus
fcitx-module-x11
fcitx-modules
fcitx-ui-classic
